const {test}=require('node:test');
const assert=require('node:assert/strict');
const vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
function node(){const events={},attrs={},flags=new Set();let capture=null;return {events,attrs,isConnected:true,style:{setProperty(){}},classList:{add:x=>flags.add(x),remove:x=>flags.delete(x),toggle:(x,on)=>on?flags.add(x):flags.delete(x)},setAttribute:(k,v)=>attrs[k]=v,addEventListener:(k,f)=>events[k]=f,setPointerCapture:id=>capture=id,hasPointerCapture:id=>capture===id,releasePointerCapture:()=>capture=null};}
function runtime(){const timers=[];const window={MiftahGame:{LettersArt:{}},removeEventListener(){}};const context={window,setTimeout:f=>(timers.push(f),timers.length),clearTimeout(){},setInterval:()=>1,clearInterval(){}};for(const file of ['LettersGame.js','MiniGames.js'])vm.runInNewContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),context);return {ns:window.MiftahGame,timers};}
function bar(){const {ns,timers}=runtime(),sound=node(),dot=node();let opens=0,cancels=0;const el={isConnected:true,querySelector:s=>s==='.lg-sound'?sound:s==='.lg-grownup-dot'?dot:null};const game=Object.create(ns.LettersGame.prototype);Object.assign(game,{root:{querySelectorAll:s=>s==='.lg-sound'?[sound]:[]},sound:{enabled:true,play(){}},stopSpeech(){cancels++},renderGrownup(){opens++}});game.wireTopBar(el);return {game,sound,dot,el,timers,opens:()=>opens,cancels:()=>cancels};}
test('mute cancels speech once and synchronizes the control state',()=>{const b=bar();b.sound.events.click();assert.equal(b.game.sound.enabled,false);assert.equal(b.cancels(),1);assert.equal(b.sound.attrs['aria-pressed'],'false');b.sound.events.click();assert.equal(b.game.sound.enabled,true);assert.equal(b.cancels(),1);});
test('adult hold rejects key repeat, early release and stale timer callbacks',()=>{const b=bar();const e={key:'Enter',preventDefault(){}};b.dot.events.keydown(e);b.dot.events.keydown({...e,repeat:true});assert.equal(b.timers.length,1);b.dot.events.keyup(e);b.timers[0]();assert.equal(b.opens(),0);b.dot.events.keydown(e);b.timers[0]();assert.equal(b.opens(),0);b.timers[1]();b.timers[1]();assert.equal(b.opens(),1);});
test('adult hold cancels on blur and cannot navigate from an old screen',()=>{const b=bar();b.dot.events.pointerdown({button:0,pointerId:2});b.dot.events.blur();b.timers[0]();assert.equal(b.opens(),0);b.dot.events.pointerdown({button:0,pointerId:3});b.el.isConnected=false;b.timers[1]();assert.equal(b.opens(),0);});
test('Trace only paints and completes for the owning pointer',()=>{const {ns}=runtime();let strokes=0,petReactions=0,outcomes=0;const canvas=node();canvas.width=100;canvas.height=100;canvas.getBoundingClientRect=()=>({left:0,top:0,width:100,height:100});const game=Object.create(ns.LettersMiniGames.trace.prototype);Object.assign(game,{alive:true,drawing:false,canvas,g:{beginPath(){},arc(){},fill(){},moveTo(){},lineTo(){},stroke(){strokes++}},brush:4,paint:new Set(),guide:[],ctx:{petReact(){petReactions++;},reportOutcome(){outcomes++;}},pos:e=>[e.clientX,e.clientY]});game.penDown({pointerId:1,button:0,clientX:10,clientY:10});game.penMove({pointerId:2,clientX:70,clientY:70});game.penUp({pointerId:2});assert.equal(strokes,0);assert.equal(game.drawing,true);game.penMove({pointerId:1,clientX:20,clientY:20});assert.equal(strokes,1);assert.equal(petReactions,1);assert.equal(outcomes,0);game.cancelStroke({pointerId:2});assert.equal(game.drawing,true);game.cancelStroke({pointerId:1});assert.equal(game.drawing,false);assert.equal(canvas.hasPointerCapture(1),false);game.penUp({pointerId:1});assert.equal(game.drawing,false);assert.equal(outcomes,0);});
test('Trace drawing thumbnail callback fires once after completion, never on cancel',()=>{const {ns}=runtime();let thumbnails=0,outcomes=0;const paper={classList:{add(){},remove(){}},parentElement:{classList:{add(){},remove(){}}},querySelectorAll:()=>[]};const canvas=node();canvas.parentElement=paper;const game=Object.create(ns.LettersMiniGames.trace.prototype);Object.assign(game,{alive:true,advancing:false,completionReady:false,clearBtn:{disabled:false},paletteButtons:[],canvas,finishEl:{hidden:true},nextBtn:{disabled:true,focus(){}},roundIndex:0,targets:[{id:'ba',display:'ب'}],ctx:{onDrawingMade(){thumbnails++;},reportOutcome(){outcomes++;},sfx(){},petReact(){},confettiAt(){},say(){}}});game.drawing=true;game.activePointer=1;game.cancelStroke({pointerId:1});assert.equal(thumbnails,0);game.completeDrawing();game.completeDrawing();assert.equal(thumbnails,1);assert.equal(outcomes,1);});
