#!/usr/bin/env python3
"""Import the owner's OpenAI.fm audition without guessing a missing letter.

Requires the isolated voice runtime (numpy + soundfile). This source contains
25 spoken segments; the sibilant at source position 12 needs human identification.
The other mapping is supported by the submitted script and a local transcript,
not a certification of Arabic pronunciation. Nothing is generated by this script.
"""
import argparse
import hashlib
import json
import re
from pathlib import Path

import numpy as np
import soundfile as sf

ROOT = Path(__file__).resolve().parents[1]
REVIEW = ROOT / 'docs/letter-garden/reviews/marin-letters'
ASSETS = ROOT / 'assets/audio/letters/marin-v1'
EXPECTED_SHA = 'c3906c3d3702dccf0d968fe5a527502bba37eae513962991fb59284e52180a49'
SPOKEN = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, None,
          14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('source', type=Path)
    parser.add_argument('--sibilant', choices=['seen', 'sheen'])
    args = parser.parse_args()
    raw = args.source.read_bytes()
    sha = hashlib.sha256(raw).hexdigest()
    if sha != EXPECTED_SHA:
        raise SystemExit('This mapping is specific to the reviewed source. Inspect a new recording before importing it.')
    samples, sr = sf.read(args.source)
    assert samples.ndim == 1 and sr == 24000 and np.isfinite(samples).all()
    hop = int(sr * .005)
    windows = samples[:len(samples) // hop * hop].reshape(-1, hop)
    active = np.flatnonzero(np.sqrt(np.mean(windows ** 2, axis=1)) > 10 ** (-45 / 20))
    groups = [g for g in np.split(active, np.where(np.diff(active) * .005 > .12)[0] + 1) if len(g) * .005 > .06]
    assert len(groups) == 25, 'Do not force an unexpected segment count into the alphabet.'
    bounds = [(int(g[0] * hop), int((g[-1] + 1) * hop)) for g in groups]
    REVIEW.mkdir(parents=True, exist_ok=True)
    ASSETS.mkdir(parents=True, exist_ok=True)
    (REVIEW / 'original.mp3').write_bytes(raw)
    curriculum = re.findall(r'L\("([^"\n]+)", "([^"\n]+)", "([^"\n]+)"',
                            (ROOT / 'src/data/letters.js').read_text())
    assert len(curriculum) == 28
    alphabet = [dict(index=i, letter=char, name=name, input=spoken_name,
                     file=f'{i:02d}-{name.lower()}.wav')
                for i, (char, name, spoken_name) in enumerate(curriculum, 1)]
    spoken = SPOKEN.copy()
    if args.sibilant:
        spoken[11] = 12 if args.sibilant == 'seen' else 13
    clips, segments, generated, audio = {}, [], [], []
    for number, ((start, end), alphabet_index) in enumerate(zip(bounds, spoken), 1):
        # Split in the quiet gap and retain consonant tails. No pitch/time/EQ changes.
        left = 0 if number == 1 else (bounds[number - 2][1] + start) // 2
        right = len(samples) if number == len(bounds) else (end + bounds[number][0]) // 2
        left = max(left, start - int(sr * .10))
        right = min(right, end + int(sr * .16))
        clip = samples[left:right].copy()
        fade = int(sr * .004)
        clip[:fade] *= np.linspace(0, 1, fade)
        clip[-fade:] *= np.linspace(1, 0, fade)
        record = {'sourcePosition': number, 'sourceStart': round(left / sr, 4),
                  'sourceEnd': round(right / sr, 4), 'duration': round(len(clip) / sr, 4),
                  'peak': round(float(np.abs(clip).max()), 5)}
        if alphabet_index is None:
            dest = REVIEW / '12-seen-or-sheen-review.wav'
            record.update({'letter': None, 'file': dest.name, 'status': 'needs-human-identification'})
        else:
            item = alphabet[alphabet_index - 1]
            filename = item['file'].split('-', 1)[1]
            destination = ASSETS / filename
            dest = destination
            url = destination.relative_to(ROOT).as_posix()
            clips[item['input']] = url
            item['file'] = '../../../../' + url
            generated.append(item['file'])
            record.update({'letter': item['letter'], 'input': item['input'], 'file': url})
            audio.extend([clip, np.zeros(int(sr * .65))])
        sf.write(dest, clip, sr, subtype='PCM_16')
        record['sha256'] = hashlib.sha256(dest.read_bytes()).hexdigest()
        segments.append(record)
    missing = [item for item in alphabet if item['input'] not in clips]
    manifest = {
        'status': 'partial-source', 'model': 'OpenAI.fm — supplied AI speech', 'voice': 'Marin',
        'source': 'original.mp3', 'sourceSha256': sha, 'sourceSeconds': len(samples) / sr,
        'sourceSegmentCount': 25, 'sibilantIdentification': args.sibilant or 'pending',
        'letters': alphabet, 'generated': generated, 'missingLetters': [x['letter'] for x in missing],
        'disclosure': 'AI-generated voice. Transcript-assisted mapping; human pronunciation review remains pending.',
        'processing': 'Quiet-gap segmentation, 100/160 ms edge padding where available, 4 ms edge fades. Original levels and pitch preserved.',
        'segments': segments,
    }
    (REVIEW / 'batch.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n')
    sf.write(REVIEW / 'marin-available-letter-names.wav', np.concatenate(audio), sr, subtype='PCM_16')
    script = '// AI-generated letter-name clips imported from the owner-supplied OpenAI.fm recording.\n'
    script += '// Exact spoken-name lookup deliberately excludes vowel syllables and Quran words.\n'
    script += '(function (ns) {\n  ns.LETTER_VOICE_CLIPS = Object.freeze('
    script += json.dumps(clips, ensure_ascii=False, indent=2)
    script += ');\n})(window.MiftahGame || (window.MiftahGame = {}));\n'
    (ROOT / 'src/letters/LetterVoiceClips.js').write_text(script)
    print(json.dumps({'imported': len(clips), 'missing': manifest['missingLetters'], 'sourceSegments': 25}, ensure_ascii=False))


if __name__ == '__main__':
    main()
